### ISSUE TITLE
Provide steps for shrinkwrap users to fix their builds after 2.2.0 was unpublished

### ISSUE THREAD

**Issue by tlrobinson** [chalk/ansi-styles#17]
As suggested in #15 I'm opening this issue to help users who's projects/packages/builds are broken due to version 2.2.0 being unpublished, in particular in regards to version 2.2.0 being listed in `npm-shrinkwrap.json`.

I manually edited my `npm-shrinkwrap.json` but this is annoying and error prone, and I'd like to know if there's a better way. Deleting `npm-shrinkwrap.json` and re-running `npm shrinkwrap` is not always an option, as I'd like to keep most of the packages locked to their current versions.

**Comment by Qix-** [comment]
// @sindresorhus

**Comment by dr-nafanya** [comment]
Manual search/replace of `ansi-styles@2.2.0` to `ansi-styles@2.2.1` in `npm-shrinkwrap.json` *does* work.

**Comment by Qix-** [comment]
Thank you @dr-nafanya.

**Comment by Qix-** [comment]
Keeping open for discovery.

**Comment by tlrobinson** [comment]
Yes, manually editing works in this case, however it leaves the `color-convert` dependency that was added in 2.2.0 in `npm-shrinkwrap.json`, which I think is harmless (aside from a little bit of wasted bandwidth), but if a dependency were *added* rather than *removed* this probably wouldn't work.

**Comment by Qix-** [comment]
It shouldn't be a problem. The new version of `color-convert` was designed to work with the existing chalk API.

Good catch though :+1:

**Comment by desbo** [comment]
If it's any help you can use https://gist.github.com/desbo/906326b08c05aa09e2fe to replace any occurrences of `ansi-styles` at 2.2.0 with 2.2.1 in `npm-shrinkwrap.json`.

**Comment by xcatliu** [comment]
Thanks @dr-nafanya 
Problem fixed when I manually replaced `ansi-styles@2.2.0` to `ansi-styles@2.2.1` in `npm-shrinkwarp.json`

`ansi-styles` is an awesome module to control styles in terminal, but please known [it's a bad behavior to remove versions of a library that others are depending on](https://docs.npmjs.com/cli/unpublish)

Anyway, many thanks to @Qix- for the awesome library!

**Comment by Qix-** [comment]
@xcatliu We're aware of the problems with unpublish :+1: Checkout the [post mortem](https://github.com/chalk/ansi-styles/issues/15#issuecomment-202589714).
