### ISSUE TITLE
Running xo reports error: Avoid using extended native objects

### ISSUE THREAD

**Issue by shaochuancs** [chalk/ansi-styles#21]
When running xo to test code, it reports the following error.

test.js:5:26    Avoid using extended native objects

In test.js, this error is due to the use of "Object.entries" -- according to [node.green](http://node.green/), "Object.entries" is not well supported. Even in Node v6.9.1, it can only be available with "--harmony" tag.

Suggest using "Object.keys" instead of "Object.entries".

**Comment by shaochuancs** [comment]
#22

**Comment by sindresorhus** [comment]
AVA transpiles test files with Babel. So we can use it there.
