### ISSUE TITLE
Different versions between npm and this repo

### ISSUE THREAD

**Issue by YerkoPalma** [chalk/ansi-styles#23]
I have a weird error. I copied the example from the readme

```javascript
const style = require('ansi-styles');

console.log(style.color.ansi256.rgb(199, 20, 250) + 'Hello world!' + style.color.close);
```

And it fails inmediatly with `TypeError: Cannot read property 'ansi256' of undefined`.
So I compared the source that I downloaded with npm and I found it is quite different from what is in this repo (I copied the downloaded code below). Now, I think thats strange, but I noticed that the version in the package.json file of this repo is **`2.1.0`**, while the version published to npm is **`2.2.1`**. I think that tha's the problem. Now, I'm not sure why the last version remove the color feature, could you re add it?

```javascript
'use strict';

function assembleStyles () {
	var styles = {
		modifiers: {
			reset: [0, 0],
			bold: [1, 22], // 21 isn't widely supported and 22 does the same thing
			dim: [2, 22],
			italic: [3, 23],
			underline: [4, 24],
			inverse: [7, 27],
			hidden: [8, 28],
			strikethrough: [9, 29]
		},
		colors: {
			black: [30, 39],
			red: [31, 39],
			green: [32, 39],
			yellow: [33, 39],
			blue: [34, 39],
			magenta: [35, 39],
			cyan: [36, 39],
			white: [37, 39],
			gray: [90, 39]
		},
		bgColors: {
			bgBlack: [40, 49],
			bgRed: [41, 49],
			bgGreen: [42, 49],
			bgYellow: [43, 49],
			bgBlue: [44, 49],
			bgMagenta: [45, 49],
			bgCyan: [46, 49],
			bgWhite: [47, 49]
		}
	};

	// fix humans
	styles.colors.grey = styles.colors.gray;

	Object.keys(styles).forEach(function (groupName) {
		var group = styles[groupName];

		Object.keys(group).forEach(function (styleName) {
			var style = group[styleName];

			styles[styleName] = group[styleName] = {
				open: '\u001b[' + style[0] + 'm',
				close: '\u001b[' + style[1] + 'm'
			};
		});

		Object.defineProperty(styles, groupName, {
			value: group,
			enumerable: false
		});
	});

	return styles;
}

Object.defineProperty(module, 'exports', {
	enumerable: true,
	get: assembleStyles
});

```

**Comment by sindresorhus** [comment]
We haven't published the version in master yet.

**Comment by YerkoPalma** [comment]
haha should have checked branches first :smile: 

So, that means that you are removing the ansi wrappers? so now I can't use custom colors like this `console.log(style.color.ansi256.rgb(199, 20, 250) + 'Hello world!' + style.color.close)`?

**Comment by Qix-** [comment]
We're adding them ;) They just haven't been published yet.
