### ISSUE TITLE
Exported Categories

### ISSUE THREAD

**Issue by shellscape** [chalk/ansi-styles#24]
Would the maintainers be open to an export style that groups styles and colors separately? At present version, all styles and colors are exported in the same object on the same level.

Additionally, it appears that the documentation in the README is no longer correct. `style.color` is now undefined.

**Comment by sindresorhus** [comment]
> Would the maintainers be open to an export style that groups styles and colors separately?

That's already available, see: https://github.com/chalk/ansi-styles#advanced-usage

> Additionally, it appears that the documentation in the README is no longer correct. style.color is now undefined.

The readme is for a yet to be released version.

**Comment by shellscape** [comment]
@sindresorhus I may be eating paint chips here, but if the README is for a yet to be released version, and the #advanced-usage section is in the README, and `style.color` (which is presently `undefined`) is part of the as yet unreleased version, am I hosed until that version is released? If so, can that be released on a beta tag or similar?

**Comment by sindresorhus** [comment]
Readme for latest released version: https://github.com/chalk/ansi-styles/tree/95c59b23be760108b6530ca1c89477c21b258032#advanced-usage You can also find this on its npm page.

**Comment by shellscape** [comment]
wonderful. thanks for pointing that out
