### ISSUE TITLE
NPM and Github versions out of sink?

### ISSUE THREAD

**Issue by joshuacoles** [chalk/ansi-styles#25]
I was attempting to install the package and noticed that I was missing the code for ANSI 256 and 16m as well as getting a different version (`2.2.1`) than is in the master branch (`2.1.0`).

I believe that the NPM package is being published from branch `2.2.1` which I assume was created in response to #15. This branch does not contain any commit since a42e120 on July 01 2015. Am I correct in assuming that this can be rectified in by bumping the version in the main repo to `2.2.2` and then publishing from there?

Many thanks, Josh

**Comment by Qix-** [comment]
Please see #23.

**Comment by joshuacoles** [comment]
And I forgot to look in closed issues, sorry!!
