### ISSUE TITLE
Possible to implement bright colors?

### ISSUE THREAD

**Issue by roblav96** [chalk/ansi-styles#26]
I used to use https://github.com/medikoo/cli-color until I fell in love with `ansi-styles` simplicity 👍 

One thing I do miss is the ability to use bright colors. I took at look at [their source](https://github.com/medikoo/cli-color/blob/master/lib/sgr.js#L34) but it looks like an achient hyroglyphics maze.

What are your thoughts on adding `light` to the list of modifiers? Great work mate!

**Comment by Qix-** [comment]
Hi there, welcome! :Man_dancing:

I agree, we should have the light colors on the list! I can submit a PR for that here in a bit. However, an alternative that will return the bright codes is to use the `.color.ansi(r, g, b)` and `.bgColor.ansi(r, g, b)` functions. For example, `.color.rgb(255, 0, 0)` will return `[91m` - the bright red code! :)

Good suggestion :)

**Comment by roblav96** [comment]
@Qix- I've been using the rgb so far which is definitely a killer feature. Although the colors wouldn't correlate with my terminal theme which is the only reason I'm wondering about this feature. 👍

**Comment by Qix-** [comment]
@roblav96 If you use the ansi 16 version, they should. :)

Ill still add bright colors, though!

**Comment by roblav96** [comment]
@Qix- That would be totes mc🐐s awesome. Thanks mate!
