### ISSUE TITLE
Not working correctly in Windows console

### ISSUE THREAD

**Issue by unional** [chalk/ansi-styles#27]
Reference:  https://github.com/avajs/ava/issues/1124 
What works in windows: https://github.com/unional/aurelia-logging-color/blob/master/src/AnsiBrush.ts#L32

**Comment by Qix-** [comment]
That's exactly what we're doing. This isn't an ansi-styles bug, but alternatively an AVA bug.

**Comment by unional** [comment]
It does not. I trace through the code and in windows environment (at least when running in ava) the `offset` in https://github.com/chalk/ansi-styles/blob/master/index.js#L6 is incorrect.

**Comment by unional** [comment]
You can easily test it yourself by:

```sh
npm i chalk ava aurelia-logging aurelia-logging-color
```
```js
var chalk = require('chalk')
var logging = require('aurelia-logging')
var color = require('aurelia-logging-color')
var test = require('ava')

logging.setLevel(logging.logLevel.debug)
var log = logging.getLogger('some log')
logging.addAppender(new color.ColorAppender())

test(_t => {
  console.log(chalk.bgGreen('suppose to be green'))
  log.debug('log something')
})
```

**Comment by unional** [comment]
Actually, let me show you the result:
![image](https://cloud.githubusercontent.com/assets/3254987/22640334/0305baf2-ec07-11e6-8aab-b3460a0a178c.png)

**Comment by Qix-** [comment]
What is the `offset`? That's just for foreground/background. It should either be 0 or 10.

`supports-color` is probably reporting that it's not enabled, which most of our tickets here address pretty extensively. Please check those to figure out if supports-color is reporting that it's not enabled.

This is still an AVA issue until I see otherwise.

**Comment by Qix-** [comment]
Locking so we don't duplicate conversations.
