### ISSUE TITLE
Bold seem broken

### ISSUE THREAD

**Issue by antoine-pous** [chalk/ansi-styles#32]
Hi!

In `inquirer` package answers are empty. After investigating it appear that `chalk.bold` return nothing.

Incriminated code: https://github.com/SBoudrias/Inquirer.js/blob/master/lib/prompts/base.js#L129
Related issue: https://github.com/SBoudrias/Inquirer.js/issues/536

**Note:** I have tested with the latest chalk version and the issue is still present

Thank you !

**Comment by Qix-** [comment]
@sindresorhus we really need an issues template :o 

Operating system and version? Command prompt/terminal emulator name and version? Value of `TERM` environment variable? Which shell are you using (bash / zsh / N/A)?

All of our colors and styles are ANSI compliant, so most terminals are going to treat them the same.

**Comment by antoine-pous** [comment]
Sorry for the lack of informations, here's the configuration:

- **OS:** Ubuntu  16.10
- **Terminal:** xterm 324
- **Emulator:** Gnome terminal 3.20.2 (VTE 0.44.2)
- **$TERM:** xterm-256color
- **Shell:** bash
- **NodeJS:** 7.9.0

**Comment by Qix-** [comment]
Can you take a screenshot of the following command and post it back here?

```shell
$ node -e 'console.log("this is a \x1b[1mtest\x1b[m command")'
```

**Comment by antoine-pous** [comment]
![selection_319](https://cloud.githubusercontent.com/assets/7486600/26443230/bd4b7ff2-4137-11e7-8dbd-83b9d73d1099.png)

**Comment by Qix-** [comment]
This isn't a problem with chalk (or any software that uses chalk), it's a problem with your terminal emulator. For some reason, its blanking out bold escapes (I've never seen that before).

Make sure you're up to date, and try using another terminal emulator. Sorry you're experiencing this, these kinds of bugs are frustrating. :/
