### ISSUE TITLE
NPM install error

### ISSUE THREAD

**Issue by oliveiradouglas** [chalk/ansi-styles#34]
Hello!
I am trying run `npm install` command and am getting the error bellow:

`npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz`

Any idea?

**Comment by sindresorhus** [comment]
Open an issue on npm.

**Comment by ashleyryan** [comment]
I'm getting the same. The versions property of https://registry.npmjs.org/ansi-styles/ doesn't include 2.2.0, but the 'time" property does show a 2.2.0

**Comment by Simounet** [comment]
Hi there,
I've got the same issue and I saw that the 2.2.0 tag is not on your Github repo anymore. Maybe not an npm issue after all.

**Comment by Qix-** [comment]
2.2.0 got unpublished about a year ago, I don't exactly remember why but I know we had a brief outage over at Chalk proper. Please use 2.2.1 instead (unless your version selectors are too strict, this shouldn't be happening). I'm not sure where this came from since this hasn't been a problem for over a year, though I suspect it might have to do with npm@5.

**Comment by Simounet** [comment]
Thanks for your quick reply.
I investigate and found some packages using `chalk@1.1.1` that needs `ansi-styles@2.2.0`. I can take [gulp](https://github.com/gulpjs/gulp/blob/v3.9.1/package.json#L30) as an example. I'm using `npm shrinkwrap` and it forces `npm install` to use the exact versions. I'm on `npm@4.6.1` by the way.

**Comment by Qix-** [comment]
Chalk 1.1.1 is also an old version that was problematic. It should be pulling 1.1.3 IIRC. Not sure why this is surfacing now as we haven't had problems with this for over a year.

**Comment by eschwartz** [comment]
> 2.2.0 got unpublished about a year ago
> Please use 2.2.1 instead

I don't necessarily have control over which version I'm using, as it's a dependency of a dependency.
Unpublishing seems like it's going to cause all sorts of problems for people (I thought npm stopped allowing un-publishing after the whole left-pad debacle).
Any chance you could re-publish v2.2.0, maybe from the same commit as v2.2.1?

**Comment by Qix-** [comment]
What is the semver selector they're using? It should be automatically pulling 2.2.1 as it's a bugfix release.
