### ISSUE TITLE
Did the 2.2.0 release disappear?

### ISSUE THREAD

**Issue by benjaminapetersen** [chalk/ansi-styles#38]
I recently began experiencing the following errors:

```
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
npm WARN retry will retry, error on last attempt: Error: fetch failed with status code 404
npm ERR! fetch failed https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
```

This is a dependency of a dependency, not something I'm directly dependent upon.  Wondering if  the `2.2.1` intentionally replaces due to a security issue?

**Comment by Qix-** [comment]
Yes - this was a problem that was resolved ages ago that NPM has now resurfaced with their sub-par `package-lock.json` logic I think. See npm/npm#17723.

Either use Yarn or try to blow away your `node_modules/` and try again. It _should_ be pulling ansi-styles 2.2.1.

**Comment by benjaminapetersen** [comment]
Ok thanks!  Fishing through my dependencies to try to figure out which one keeps asking for `2.2.0` & won't let it bump ☹️

**Comment by Qix-** [comment]
Using Yarn will show you the dependency stack - try that first.
