### ISSUE TITLE
Unable to install the package

### ISSUE THREAD

**Issue by captainkovalsky** [chalk/ansi-styles#39]
There is an 404 error during the package installation

## Environment
```
node: 5.4.2
npm: v8.4.0
```

### Steps to reproduce:
1. run `npm i ansi-styles`

#### Actual result:
```
⋊> ~/P/c/p/about ⨯ npm install ansi-styles                                                            19:34:45
npm ERR! code E404
npm ERR! 404 Not Found: ansi-styles@https://registry.npmjs.org/ansi-styles/-/ansi-styles-2.2.0.tgz
```

#### Expected result:
package should be install successfully

**Comment by sindresorhus** [comment]
Use the npm issue tracker for npm install issues: https://github.com/npm/npm/issues
