### ISSUE TITLE
Why the open/close API

### ISSUE THREAD

**Issue by aaronbeall** [chalk/ansi-styles#42]
Why does the API expose `.open` and `.close` on everything, even though `.close` is not generally specific to the style? For example `console.log(styles.red.open, "I'm red", styles.green.close, "What color am I?")` doesn't make a lot of sense...

**Comment by sindresorhus** [comment]
It's up to you to match them correctly. This module is low-level and meant for creating terminal styling libs like `chalk`. If all you want is to style string, use `chalk` instead.

**Comment by aaronbeall** [comment]
Ok, so the reason is that the API is not meant to be "friendly", but conveniently consumed by a higher level library. Fair enough. :) FYI the reason I want to use the codes directly is because libraries like `chalk` are excellent but string interpolation messes with some things native console handles well, for example native `console.log(styles.red.open, error)` vs `console.log(chalk.red(error))` outputs very different things...

**Comment by sindresorhus** [comment]
Try `console.log(chalk.red(util.inspect(error)))` or `console.log(chalk.red('%s'), error)`

**Comment by aaronbeall** [comment]
`console.log(chalk.red('%s'), error)` isn't right, `util.inspect` gives good output in most cases, but that this point it's gone full circle... I just want red output. :P

**Comment by sindresorhus** [comment]
Oops, I meant `console.log(chalk.red('%O'), error);`

**Comment by aaronbeall** [comment]
That works nicely! Thanks
