### ISSUE TITLE
Syntax error in IE11 due to arrow function currying

### ISSUE THREAD

**Issue by MirceaUngureanu** [chalk/ansi-styles#54]
There is an issue in IE11 where I think the transpiler fails to convert the code correctly.
This means it breaks any module that requires this as a dependency.
source
```
const wrapAnsi16 = (fn, offset) => (...args) => {
	const code = fn(...args);
	return `\u001B[${code + offset}m`;
};
```

vs 

transpiled in IE11
```
const wrapAnsi16 = (fn, offset) => function () {
  const code = fn.apply(colorConvert, arguments);
  return "\x1B[".concat(code + offset, "m");
};
```

Please let me know if you need any more details, and thanks for the effort you put into creating /maintaining this.

**Comment by Qix-** [comment]
You mention transpiling; if you're using a transpiler such as Babel, then you're missing some configuration. I recommend checking out their `@babel/preset-env` package for more information.

We do not transpile our releases, however - that's up to you.

**Comment by MirceaUngureanu** [comment]
Thanks for the quick reply.

**Comment by thedrew12** [comment]
@MirceaUngureanu @Qix-  How did you fix it? I'm using create-react-app and running into the same issue. I would think create-react-app would do all the transpiling already, but that doesn't seem to be the case.

**Comment by thedrew12** [comment]
Figured it out, https://github.com/facebook/create-react-app/issues/6924#issuecomment-487312199
