### ISSUE TITLE
IE11 syntax error

### ISSUE THREAD

**Issue by afrankel-sfdo** [chalk/ansi-styles#57]
Syntax error in IE11 `SCRIPT438: Object doesn't support property or method 'entries'`

index.js:123 `	for (const [groupName, group] of Object.entries(styles)) {`

Found using Create React App v3.3.1: https://github.com/facebook/create-react-app/releases/tag/v3.3.1

**Comment by Qix-** [comment]
Please open an issue with them. This is valid es2015.
