### ISSUE TITLE
Why is @types/color-name a production dependency?

### ISSUE THREAD

**Issue by DarthHater** [chalk/ansi-styles#58]
Just curious. We are using ansi-styles via chalk, and I saw this in upstream dependencies and wondered why a types file was in prod deps!

Thanks!

cc @allenhsieh

**Comment by Richienb** [comment]
@DarthHater `@types/color-name` contains an array of CSS colour names which are reused in https://github.com/chalk/ansi-styles/blob/master/index.d.ts#L24.

**Comment by bodinsamuel** [comment]
I would argue that type definitions does not belong to production even if it's a required in this package

**Comment by sindresorhus** [comment]
@bodinsamuel Your argument makes no sense. If it's not a dependency, it will cause a an error for TypeScript consumers.

You could argue that it doesn't need to be there and that method could be typed as a `string` instead, but I like type-safety and autocomplete.

**Comment by sindresorhus** [comment]
However, I'm open to inlining a union of all the colors if someone does a **good** PR for it.
