### ISSUE TITLE
Provide es5 lib output

### ISSUE THREAD

**Issue by dinony** [chalk/ansi-styles#59]
Current artifact contains arrow functions: https://unpkg.com/ansi-styles@4.2.1/index.js

Please also provide es5 output, since this lib gets hoisted into the development bundle (via CRA), to support older browsers, without having to eject CRA.

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by dinony** [comment]
Ah, ok I had the following issue:

https://create-react-app.dev/docs/supported-browsers-features

> When editing the browserslist config, you may notice that your changes don't get picked up right away. This is due to an issue in babel-loader not detecting the change in your package.json. A quick solution is to delete the node_modules/.cache folder and try again.
