### ISSUE TITLE
Add support for overline

### ISSUE THREAD

**Issue by Yash-Singh1** [chalk/ansi-styles#66]

**Comment by Qix-** [comment]
PR welcome. :)

**Comment by sindresorhus** [comment]
Such PR should come with tests, docs (which mention which terminals support this style), and index.d.ts updates.

**Comment by Yash-Singh1** [comment]
I will tackle this later.

**Comment by sindresorhus** [comment]
Fixed by https://github.com/chalk/ansi-styles/commit/80dcce218e1403480696d8c17bc4c24d052bbf09.
