### ISSUE TITLE
Can't import into TypeScript node project

### ISSUE THREAD

**Issue by electrovir** [chalk/ansi-styles#72]
I've been using `v5.2.0` fine for a while. I just upgraded to `v6.1.0` and I can't get the `ansi-styles` import to work properly anymore.

Here's my `v5.2.0` code which used to work:

```typescript
import * as styles from 'ansi-styles';
console.log(styles.blue.open)
```

After upgrading to `v6.1.0` I get the following TypeScript error:

```
error TS2339: Property 'blue' does not exist
```

If I change the code to the following (with `v6.1.0`) then TypeScript is happy:

```typescript
import styles from 'ansi-styles';
console.log(styles.blue.open);
```

but now I get the following error:

```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: .../node_modules/ansi-styles/index.js
require() of ES modules is not supported.
require() of .../node_modules/ansi-styles/index.js from <my-transpiled-file-path> is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from .../node_modules/ansi-styles/package.json.
```

I also tried adding `"esModuleInterop": true,` to my `tsconfig.json` file and that did not help.

**Comment by sindresorhus** [comment]
Please read the release notes.

**Comment by electrovir** [comment]
I think I found it! I spent a while trying to find some kind of documentation like this before opening this issue but failed. At least now it's tracked in this issue.

For any others, the "release notes" in question appear to be this: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
