### ISSUE TITLE
Add support for superscript and subscript

### ISSUE THREAD

**Issue by Yash-Singh1** [chalk/ansi-styles#75]
https://en.wikipedia.org/wiki/ANSI_escape_code#:~:text=73,75

**Comment by sindresorhus** [comment]
According to Wikipedia, it's only implemented in mintty. I don't think it makes sense for us to support something with such limited usefulness.

If you want to see this happen, you could open an issue on all popular terminals and ask them to implement it.

**Comment by Qix-** [comment]
I don't see this happening anytime soon, probably best just to assume it won't happen.
