### ISSUE TITLE
Problem from version`5+` to Regex when using ReactNative Hermes engine

### ISSUE THREAD

**Issue by alimek** [chalk/ansi-styles#76]
Problem is in that line: https://github.com/chalk/ansi-styles/blob/cd0b0cb59337bfd7d3669b2d0fcde7ff661a83a6/index.js#L132

When generating hermes bytecode it is failing because `Invalid regular expression: Quantifier has nothing to repeat`

Some info here: https://github.com/facebook/hermes/issues/89
 
I also think it may be related to `https://github.com/facebook/jest/blob/master/packages/pretty-format/package.json` and its `pretty-format` package.

**Comment by sindresorhus** [comment]
This package targets Node.js 12. For any other platform/engine, you're on your own. We don't plan to add any workarounds for Hermes.
