### ISSUE TITLE
'ansi-styles@2.2.0' is not in the npm registry.

### ISSUE THREAD

**Issue by bishanqbs** [chalk/ansi-styles#77]
Please restore or add this.

![image](https://user-images.githubusercontent.com/75665081/128605386-ce6e901c-1adb-48a0-bf8d-275c906a3153.png)

**Comment by Qix-** [comment]
Yep, doesn't appear to have ever been a version we've published. Nothing we can do, someone's added the wrong version somewhere in your codebase.

There's nothing actionable for us to do here.

`npm ls` is your friend here. Good luck!
